---
- name: Check Installation Status
  hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    db_user: postgres
    db_password: postgres

  tasks:
    # Node.js確認
    - name: Check Node.js version
      shell: node --version
      register: node_version
      changed_when: false

    - name: Display Node.js version
      debug:
        var: node_version.stdout

    # PostgreSQL確認
    - name: Check PostgreSQL version
      shell: psql --version
      register: psql_version
      changed_when: false

    - name: Check PostgreSQL service status
      systemd:
        name: postgresql
        state: started
      check_mode: yes
      register: psql_status
      changed_when: false

    - name: List PostgreSQL databases
      become_user: postgres
      environment:
        PGPASSWORD: "{{ db_password }}"
      shell: |
        psql -U {{ db_user }} -c "\l"
      register: db_list
      changed_when: false

    # Nginx確認
    - name: Check Nginx version
      shell: nginx -v
      register: nginx_version
      changed_when: false

    - name: Check Nginx service status
      systemd:
        name: nginx
        state: started
      check_mode: yes
      register: nginx_status
      changed_when: false

    # Firewall確認
    - name: Check firewalld version
      shell: firewall-cmd --version
      register: firewall_version
      changed_when: false

    - name: Check firewalld service status
      systemd:
        name: firewalld
        state: started
      check_mode: yes
      register: firewall_status
      changed_when: false

    - name: Check firewall configuration
      shell: |
        sudo firewall-cmd --list-all
      register: firewall_config
      changed_when: false

    # pgAdmin確認
    - name: Check pgAdmin installation
      shell: rpm -q pgadmin4-web
      register: pgadmin_version
      changed_when: false
      failed_when: false

    - name: Check pgAdmin service through Nginx
      uri:
        url: http://localhost/pgadmin5/
        return_content: yes
      register: pgadmin_response
      failed_when: false

    # 結果表示
    - name: Display Installation Status
      debug:
        msg:
          - "Node.js Version: {{ node_version.stdout }}"
          - "PostgreSQL Version: {{ psql_version.stdout }}"
          - "PostgreSQL Service: {{ 'Running' if not psql_status.changed else 'Not Running' }}"
          - "Nginx Version: {{ nginx_version.stderr }}"
          - "Nginx Service: {{ 'Running' if not nginx_status.changed else 'Not Running' }}"
          - "Firewall Version: {{ firewall_version.stdout }}"
          - "Firewall Service: {{ 'Running' if not firewall_status.changed else 'Not Running' }}"
          - "pgAdmin Version: {{ pgadmin_version.stdout }}"
          - "pgAdmin Web Access: {{ 'Available' if pgadmin_response.status == 200 else 'Not Available' }}"

    - name: Display Database List
      debug:
        var: db_list.stdout_lines

    - name: Display Firewall Configuration
      debug:
        var: firewall_config.stdout_lines