---
- name: Configure Web Server
  hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    db_name: training
    db_user: postgres
    db_password: postgres
  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      
    - name: Install NodeSource repository
      shell: |
        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      args:
        creates: /etc/yum.repos.d/nodesource-el8.repo
      
    - name: Install required packages
      dnf:
        name:
          - postgresql15-server
          - nginx
          - firewalld
          - nodejs
        state: present

    - name: Initialize PostgreSQL database
      command: postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Configure pg_hba.conf
      copy:
        dest: /var/lib/pgsql/data/pg_hba.conf
        content: |
          # TYPE  DATABASE        USER            ADDRESS                 METHOD
          local   all            all                                     trust
          host    all            all             127.0.0.1/32            trust
          host    all            all             ::1/128                 trust
        owner: postgres
        group: postgres
        mode: '0600'

    - name: Start PostgreSQL service
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Check if database exists
      become: yes
      become_user: postgres
      environment:
        PGPASSWORD: "{{ db_password }}"
      shell: |
        psql -U {{ db_user }} -tAc "SELECT 1 FROM pg_database WHERE datname='{{ db_name }}'"
      register: db_exists
      changed_when: false

    - name: Check if password is set
      become: yes
      become_user: postgres
      environment:
        PGPASSWORD: "{{ db_password }}"
      shell: |
        psql -U {{ db_user }} -tAc "SELECT rolpassword FROM pg_authid WHERE rolname='{{ db_user }}'" | grep -q "^md5"
      register: password_set
      changed_when: false
      failed_when: false

    - name: Setup PostgreSQL
      become: yes
      become_user: postgres
      environment:
        PGPASSWORD: "{{ db_password }}"
      shell: |
        {% if not password_set.rc == 0 %}
        psql -U {{ db_user }} -c "ALTER USER {{ db_user }} WITH PASSWORD '{{ db_password }}';"
        {% endif %}
        {% if db_exists.stdout != "1" %}
        psql -U {{ db_user }} -c "CREATE DATABASE {{ db_name }};"
        {% endif %}
      register: db_setup
      failed_when: db_setup.rc != 0
      changed_when: db_setup.stdout != ""

    - name: Update pg_hba.conf for password authentication
      copy:
        dest: /var/lib/pgsql/data/pg_hba.conf
        content: |
          # TYPE  DATABASE        USER            ADDRESS                 METHOD
          local   all            all                                     md5
          host    all            all             127.0.0.1/32            md5
          host    all            all             ::1/128                 md5
        owner: postgres
        group: postgres
        mode: '0600'

    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

    - name: Start and enable firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Allow HTTP through firewall
      become: yes
      command: firewall-cmd --permanent --add-service=http
      register: result
      changed_when: result.rc == 0
      ignore_errors: yes

    - name: Allow HTTPS through firewall
      become: yes
      command: firewall-cmd --permanent --add-service=https
      register: result
      changed_when: result.rc == 0
      ignore_errors: yes

    - name: Reload firewall
      become: yes
      command: firewall-cmd --reload
      register: result
      changed_when: result.rc == 0

    - name: Check PostgreSQL databases
      become: yes
      become_user: postgres
      environment:
        PGPASSWORD: "{{ db_password }}"
      shell: |
        psql -U {{ db_user }} -c "\l"
      register: db_list
      changed_when: false

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes